package codegen

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
)

func GenerateAPI(authCfg *AuthConfig) {
	GenerateAPIWithSkip(authCfg, make(map[string]bool))
}

func GenerateAPIWithSkip(authCfg *AuthConfig, resourcesToSkip map[string]bool) {
	cfg, err := LoadConfig()
	if err != nil {
		log.Fatalf("failed to load config: %v", err)
	}

	modelsDir, err := GetModelsPath(cfg)
	if err != nil {
		log.Fatalf("failed to get models path: %v", err)
	}

	apiDir, err := GetResourcesPath(cfg)
	if err != nil {
		log.Fatalf("failed to get resources path: %v", err)
	}

	dtosDir, err := GetDTOsPath(cfg)
	if err != nil {
		log.Fatalf("failed to get DTOs path: %v", err)
	}

	if err := os.MkdirAll(apiDir, 0755); err != nil {
		log.Fatalf("failed to create resources dir: %v", err)
	}

	if err := os.MkdirAll(dtosDir, 0755); err != nil {
		log.Fatalf("failed to create api/dtos dir: %v", err)
	}

	files, err := os.ReadDir(modelsDir)
	if err != nil {
		log.Fatalf("failed to read models dir: %v", err)
	}

	// Track generated resources for route registration
	var generatedResources []string

	for _, file := range files {
		if !strings.HasSuffix(file.Name(), ".go") {
			continue
		}

		filePath := filepath.Join(modelsDir, file.Name())
		structs := parseStructs(filePath)

		for _, s := range structs {
			resourceName := strings.ToLower(s)
			if resourcesToSkip[resourceName] {
				log.Printf("⏭️  Skipping resource: %s", resourceName)
				continue
			}
			generateDTOForStruct(dtosDir, s)
			generateResourceForStruct(apiDir, s, authCfg)
			generatedResources = append(generatedResources, s)
		}
	}

	// Generate routes.go
	generateRoutesFile(generatedResources, authCfg)
}

// generateRoutesFile generates the routes.go file with auto-registered routes
func generateRoutesFile(resources []string, authCfg *AuthConfig) {
	cfg, err := LoadConfig()
	if err != nil {
		log.Fatalf("failed to load config: %v", err)
	}

	routesPath, err := GetRoutesPath(cfg)
	if err != nil {
		log.Fatalf("failed to get routes path: %v", err)
	}

	var registrations strings.Builder
	for _, resource := range resources {
		registrations.WriteString(fmt.Sprintf("\tRegister%sRoutes(app, db, paginationLimit, paginationMaxLimit, pluginRegistry)\n", resource))
	}

	code := fmt.Sprintf(`// Code generated by GoREST. DO NOT EDIT.

package resources

import (
	"github.com/gofiber/fiber/v2"
	"github.com/nicolasbonnici/gorest/database"
	"github.com/nicolasbonnici/gorest/plugin"
)

func RegisterGeneratedRoutes(app *fiber.App, db database.Database, paginationLimit, paginationMaxLimit int, pluginRegistry *plugin.PluginRegistry) {
%s}
`, registrations.String())

	if err := os.WriteFile(routesPath, []byte(code), 0644); err != nil {
		log.Fatalf("failed to write routes.go: %v", err)
	}
	log.Printf("🔀 Generated route registration → %s", routesPath)
}

// All functions moved to separate files:
// - apigen_ast.go: AST parsing functions
// - apigen_dto.go: DTO generation functions
// - apigen_resource.go: Resource generation functions
// - apigen_types.go: Type conversion and utility functions
